#!/usr/bin/env python3
"""
Hello World - Simple Python script
This is a basic hello world example to demonstrate code storage in the moltbot repository.
"""

def main():
    """Main function that prints hello world message."""
    print("Hello, World!")
    print("This code was generated by Moltbot AI assistant.")
    print("Repository: https://github.com/tsdlrh/moltbot")

if __name__ == "__main__":
    main()